#!/usr/bin/env bash
# Reorganizes DSA-problems repo: adds .py extensions, fixes names/typos,
# and sorts every solution into a topic folder. Uses `git mv` so history
# and blame are preserved. Run this from the ROOT of your local clone.
set -e

declare -A MAP=(
  ["./. Find First and Last Position of Element in Sorted Array"]="Binary_Search/firstAndLastPositionOfElement.py"
  ["1386. Cinema Seat Allocation"]="Bit_Manipulation/cinemaSeatAllocation.py"
  ["191. Number of 1 Bits"]="Bit_Manipulation/numberOf1Bits.py"
  ["3069. Distribute Elements Into Two Arrays"]="Arrays/distributeElementsIntoTwoArrays.py"
  ["Alpha-Patterns"]="Patterns/alphabetPatterns.py"
  ["Array Search"]="Binary_Search/arraySearch.py"
  ["Binary Search"]="Binary_Search/binarySearch.py"
  ["Check K-th Bit"]="Bit_Manipulation/checkKthBit.py"
  ["Check if Array is Sorted"]="Arrays/checkIfArrayIsSorted.py"
  ["Contains Duplicate"]="Hashing/containsDuplicate.py"
  ["Count Inversions"]="Sorting/countInversions.py"
  ["CountPrime"]="Math/countPrimes.py"
  ["Divide Two Integers"]="Bit_Manipulation/divideTwoIntegers.py"
  ["Find Minimum in Rotated Sorted Array"]="Binary_Search/findMinimumInRotatedSortedArray.py"
  ["First and Last in Unosrted"]="Arrays/firstAndLastOccurrence.py"
  ["Index of the First Occurrence in a String"]="Strings/indexOfFirstOccurrence.py"
  ["Intersection of Two Arrays II"]="Hashing/intersectionOfTwoArraysII.py"
  ["Largest in Array"]="Arrays/largestInArray.py"
  ["Max Consecutive Ones"]="Arrays/maxConsecutiveOnes.py"
  ["Max-value"]="Arrays/findLargestElement.py"
  ["Merge Intervals"]="Arrays/mergeIntervals.py"
  ["Merge Sorted Array"]="Two_Pointers/mergeSortedArray.py"
  ["Minimum Window Substring"]="Strings/minimumWindowSubstring.py"
  ["Missing And Repeating"]="Arrays/missingAndRepeating.py"
  ["Missing Number"]="Arrays/missingNumber_sumMethod.py"
  ["Naive Pattern Searching algorithm"]="Strings/naivePatternSearching.py"
  ["Number-Patterns"]="Patterns/numberPatterns.py"
  ["Pascal's Triangle"]="Dynamic_Programming/pascalsTriangle.py"
  ["Remove Duplicates from Sorted Array"]="Two_Pointers/removeDuplicatesFromSortedArray.py"
  ["Reverse-Of-Number"]="Math/reverseInteger.py"
  ["Rotate Array by K Places"]="Arrays/rotateArrayByKPlaces.py"
  ["Search in Rotated Sorted Array"]="Binary_Search/searchInRotatedSortedArray.py"
  ["Single Number"]="Bit_Manipulation/singleNumber.py"
  ["Sort Colors"]="Two_Pointers/sortColors.py"
  ["Star-Patterns"]="Patterns/starPatterns.py"
  ["bubble_sort"]="Sorting/bubbleSort.py"
  ["countBits"]="Bit_Manipulation/countBits.py"
  ["countDigits"]="Math/countDigits.py"
  ["countZeroes"]="Binary_Search/countZeroes.py"
  ["findMaximumXOR"]="Bit_Manipulation/findMaximumXOR.py"
  ["findPeakElement"]="Binary_Search/findPeakElement.py"
  ["firstUniqChar"]="Hashing/firstUniqChar.py"
  ["fourSumCount"]="Hashing/fourSumCount.py"
  ["frequencySort"]="Hashing/frequencySort.py"
  ["getMinMax"]="Arrays/getMinMax.py"
  ["groupAnagrams"]="Hashing/groupAnagrams.py"
  ["guessNumber"]="Binary_Search/guessNumber.py"
  ["isAnagram"]="Hashing/isAnagram.py"
  ["isIsomorphic"]="Hashing/isIsomorphic.py"
  ["isPalindrome"]="Two_Pointers/isPalindrome.py"
  ["isPowerOfTwo"]="Bit_Manipulation/isPowerOfTwo.py"
  ["leetcode hard"]="Math/smallestNumberGivenDigitProduct.py"
  ["lengthOfLongestSubstring"]="Strings/lengthOfLongestSubstring.py"
  ["lexGreaterPermutation"]="Strings/lexGreaterPermutation.py"
  ["longest palindrome substring"]="Dynamic_Programming/longestPalindromicSubstring.py"
  ["longestCommonPrefix"]="Strings/longestCommonPrefix.py"
  ["longestConsecutive"]="Hashing/longestConsecutiveSequence.py"
  ["longestSubsequence"]="Dynamic_Programming/longestSubsequence.py"
  ["majorityElement"]="Arrays/majorityElement.py"
  ["majorityElement 2"]="Arrays/majorityElementII.py"
  ["max-Profit"]="Dynamic_Programming/bestTimeToBuyAndSellStock.py"
  ["maxProduct"]="Dynamic_Programming/maximumProductSubarray.py"
  ["maxSubArray"]="Dynamic_Programming/maximumSubarray.py"
  ["maximumLengthSubstring"]="Strings/maximumLengthSubstring.py"
  ["mergeSort"]="Sorting/mergeSort.py"
  ["missingMultiple"]="Math/missingMultipleOfK.py"
  ["missingNumber"]="Arrays/missingNumber_xorMethod.py"
  ["mySqrt"]="Binary_Search/mySqrt.py"
  ["nextPermutation"]="Arrays/nextPermutation.py"
  ["rangeBitwiseAnd"]="Bit_Manipulation/rangeBitwiseAnd.py"
  ["rearrangeArray"]="Arrays/rearrangeArray.py"
  ["reverseBits"]="Bit_Manipulation/reverseBits.py"
  ["reverseString"]="Two_Pointers/reverseString.py"
  ["reverseWords"]="Strings/reverseWordsInAString.py"
  ["romanToInt"]="Math/romanToInteger.py"
  ["rotateString"]="Strings/rotateString.py"
  ["rotatematrix"]="Matrix/rotateMatrix.py"
  ["searchInsert"]="Binary_Search/searchInsertPosition.py"
  ["separateDigits"]="Arrays/separateDigits.py"
  ["setZeroes"]="Matrix/setMatrixZeroes.py"
  ["shortestPalindrome"]="Strings/shortestPalindrome.py"
  ["singleNonDuplicate"]="Binary_Search/singleNonDuplicate.py"
  ["singleNumber ll"]="Bit_Manipulation/singleNumberII.py"
  ["singleNumber lll"]="Bit_Manipulation/singleNumberIII.py"
  ["spiralOrder"]="Matrix/spiralMatrix.py"
  ["stoneGameVIII"]="Dynamic_Programming/stoneGameVIII.py"
  ["str-int"]="Strings/myAtoi.py"
  ["subarraySum"]="Arrays/subarraySumEqualsK.py"
  ["subsets"]="Backtracking/subsets.py"
  ["topKFrequent"]="Hashing/topKFrequentElements.py"
  ["twoSum"]="Hashing/twoSum.py"
  ["uniquePrimeFactors"]="Math/uniquePrimeFactors.py"
  ["wordPattern"]="Hashing/wordPattern.py"
)

mkdir -p Arrays Strings Binary_Search Bit_Manipulation Sorting Two_Pointers Hashing Dynamic_Programming Backtracking Matrix Math Patterns

for old in "${!MAP[@]}"; do
  new="${MAP[$old]}"
  if [ -e "$old" ]; then
    git mv -f "$old" "$new"
    echo "moved: $old -> $new"
  else
    echo "skip (not found): $old"
  fi
done

echo ""
echo "Done. Review with 'git status', then:"
echo "  git commit -m 'Reorganize solutions into topic folders'"
echo "  git push"
